language: node_js
sudo: false

services:
  - docker

node_js:
  - 7

install:
  - npm install

script:
  - cp config/profiles/production.json.example config/profiles/production.json
  - cp config/profiles/development.json.example config/profiles/development.json
  - npm run build
  - npm run lint

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t buckless/admin .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push buckless/admin;
    fi
